import { OnResult, preloadCacheHelper } from '../../utils/PreloadCacheHelper';
import { SelectPreloader } from '../../decorators/form/inputs/SelectInput';
import { describe, expect, it, beforeEach, jest } from '@jest/globals';

interface CacheMap {
  cache: Map<SelectPreloader<unknown>, { label: string; value: unknown }[]>;
  asyncQueue: Map<SelectPreloader<unknown>, OnResult<unknown>[]>;
}

describe('PreloadCacheHelper', () => {
  beforeEach(() => {
    // Clear the cache before each test
    (preloadCacheHelper as unknown as CacheMap).cache = new Map();
    (preloadCacheHelper as unknown as CacheMap).asyncQueue = new Map();
  });

  // Generated by AI
  it('should cache and return results for the same key', async () => {
    const mockSelectPreloaderKey = jest.fn() as SelectPreloader<number>;
    const mockOnResult = jest.fn<OnResult<number>>().mockImplementation(() => {
      return Promise.resolve();
    });

    await preloadCacheHelper.setOrGetCache(mockSelectPreloaderKey, mockOnResult);
    await preloadCacheHelper.setOrGetCache(mockSelectPreloaderKey, mockOnResult);

    expect(mockSelectPreloaderKey).toHaveBeenCalledTimes(1);
    expect(mockOnResult).toHaveBeenCalledTimes(2);
  });

  // Generated by AI
  it('should handle preload errors gracefully', async () => {
    const mockSelectPreloaderKey = jest
      .fn<SelectPreloader<number>>()
      .mockRejectedValue(new Error('Preload failed'));
    const mockOnResult = jest
      .fn<OnResult<number>>()
      .mockImplementation(async () => Promise.resolve());

    await expect(
      preloadCacheHelper.setOrGetCache(mockSelectPreloaderKey, mockOnResult)
    ).rejects.toThrow('Preload failed');

    expect(mockOnResult).not.toHaveBeenCalled();
  });

  // Generated by AI
  it('should clear async queue after successful preload', async () => {
    const mockSelectPreloaderKey = jest.fn() as SelectPreloader<number>;
    const mockOnResult = jest
      .fn<OnResult<number>>()
      .mockImplementation(async () => Promise.resolve());

    await preloadCacheHelper.setOrGetCache(mockSelectPreloaderKey, mockOnResult);

    expect((preloadCacheHelper as unknown as CacheMap).asyncQueue.has(mockSelectPreloaderKey)).toBe(
      false
    );
  });
});
