export const HardCodedLanguageOptions = [
	{ value: "zh", label: "中文" },
	{ value: "es", label: "Español" },
	{ value: "en", label: "English" },
	{ value: "hi", label: "हिन्दी" },
	{ value: "ar", label: "العربية" },
	{ value: "bn", label: "বাংলা" },
	{ value: "pt", label: "Português" },
	{ value: "ru", label: "Русский" },
	{ value: "ja", label: "日本語" },
	{ value: "pa", label: "ਪੰਜਾਬੀ" },
	{ value: "de", label: "Deutsch" },
	{ value: "jv", label: "Basa Jawa" },
	{ value: "id", label: "Bahasa Indonesia" },
	{ value: "te", label: "తెలుగు" },
	{ value: "vi", label: "Tiếng Việt" },
	{ value: "ko", label: "한국어" },
	{ value: "fr", label: "Français" },
	{ value: "mr", label: "मराठी" },
	{ value: "ta", label: "தமிழ்" },
	{ value: "tr", label: "Türkçe" },
	{ value: "it", label: "Italiano" },
	{ value: "th", label: "ไทย" },
	{ value: "fa", label: "فارسی" },
	{ value: "pl", label: "Polski" },
	{ value: "uk", label: "Українська" },
	{ value: "ml", label: "മലയാളം" },
	{ value: "gu", label: "ગુજરાતી" },
	{ value: "nl", label: "Nederlands" },
	{ value: "ro", label: "Română" },
	{ value: "hu", label: "Magyar" },
	{ value: "el", label: "Ελληνικά" },
	{ value: "cs", label: "Čeština" },
	{ value: "sv", label: "Svenska" },
	{ value: "da", label: "Dansk" },
	{ value: "fi", label: "Suomi" },
	{ value: "bg", label: "Български" },
	{ value: "he", label: "עברית" },
	{ value: "ka", label: "ქართული" },
	{ value: "hr", label: "Hrvatski" },
	{ value: "no", label: "Norsk" },
	{ value: "sk", label: "Slovenčina" },
	{ value: "lt", label: "Lietuvių" },
	{ value: "sl", label: "Slovenščina" },
	{ value: "et", label: "Eesti" },
	{ value: "lv", label: "Latviešu" },
	{ value: "sr", label: "Српски" },
	{ value: "az", label: "Azərbaycan" },
	{ value: "kk", label: "Қазақша" },
	{ value: "hy", label: "Հայերեն" },
	{ value: "ur", label: "اردو" },
	{ value: "sw", label: "Kiswahili" },
	{ value: "am", label: "አማርኛ" },
	{ value: "km", label: "ខ្មែរ" },
	{ value: "si", label: "සිංහල" },
	{ value: "my", label: "မြန်မာ" },
	{ value: "ne", label: "नेपाली" },
	{ value: "lo", label: "ລາວ" },
	{ value: "mn", label: "Монгол" },
	{ value: "uz", label: "O'zbek" },
	{ value: "tg", label: "Тоҷикӣ" },
	{ value: "ps", label: "پښتو" },
	{ value: "ku", label: "Kurdî" },
	{ value: "sd", label: "سنڌي" },
	{ value: "bo", label: "བོད་སྐད་" },
	{ value: "dz", label: "རྫོང་ཁ" },
	{ value: "mt", label: "Malti" },
	{ value: "cy", label: "Cymraeg" },
	{ value: "ga", label: "Gaeilge" },
	{ value: "gl", label: "Galego" },
	{ value: "eu", label: "Euskara" },
	{ value: "ca", label: "Català" },
	{ value: "is", label: "Íslenska" },
	{ value: "fo", label: "Føroyskt" },
	{ value: "sq", label: "Shqip" },
	{ value: "mk", label: "Македонски" },
	{ value: "bs", label: "Bosanski" },
	{ value: "af", label: "Afrikaans" },
	{ value: "zu", label: "isiZulu" },
	{ value: "xh", label: "isiXhosa" },
	{ value: "st", label: "Sesotho" },
	{ value: "tn", label: "Setswana" },
	{ value: "so", label: "Soomaali" },
	{ value: "rw", label: "Kinyarwanda" },
	{ value: "wo", label: "Wolof" },
	{ value: "ig", label: "Igbo" },
	{ value: "yo", label: "Yorùbá" },
	{ value: "ha", label: "Hausa" },
	{ value: "ln", label: "Lingála" },
	{ value: "mg", label: "Malagasy" },
	{ value: "ms", label: "Bahasa Melayu" },
	{ value: "fil", label: "Filipino" },
	{ value: "hmn", label: "Hmoob" },
	{ value: "ceb", label: "Cebuano" },
	{ value: "haw", label: "ʻŌlelo Hawaiʻi" },
	{ value: "mi", label: "Māori" },
	{ value: "sm", label: "Gagana Sāmoa" },
	{ value: "to", label: "Lea Fakatonga" },
	{ value: "ty", label: "Reo Tahiti" },
	{ value: "be", label: "Беларуская" },
	{ value: "ky", label: "Кыргызча" },
	{ value: "tk", label: "Türkmençe" },
	{ value: "tt", label: "Татарча" },
	{ value: "ba", label: "Башҡортса" },
	{ value: "cv", label: "Чӑвашла" },
	{ value: "sah", label: "Саха тыла" },
];
